# Generated by Django 5.2.1 on 2025-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
